export const CARS_REPOSITORY = 'CARS_REPOSITORY';
export const ORDERS_REPOSITORY = 'ORDERS_REPOSITORY';
export const COUPONS_REPOSITORY = 'COUPONS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const SEQUELIZE = 'SEQUELIZE';
export const APP_GUARD = 'APP_GUARD';
export const EMAIL_QUEUE = 'email queues';
export const PLACE_ORDER_EMAIL = 'place order email';
export const REGISTER_ACCOUNT_EMAIL = 'register email';
